function createfigure(X1, Y1, Z1, Size1, Color1)
%CREATEFIGURE(X1, Y1, Z1, Size1, Color1)
%  X1:  vector of scatter3 x data
%  Y1:  vector of scatter3 y data
%  Z1:  vector of scatter3 z data
%  SIZE1:  vector of scatter3 size data
%  COLOR1:  vector of scatter3 color data

%  Auto-generated by MATLAB on 15-Oct-2023 13:37:24

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure','Color',[0 0 0]);

% Create axes
axes1 = axes('Tag','PointCloud','Parent',figure1);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,Size1,Color1,'Tag','pcviewer','Marker','.');

% Create zlabel
zlabel('Z');

% Create ylabel
ylabel('Y');

% Create xlabel
xlabel('X');

% Create title
title('pc2','Color',[0.8 0.8 0.8]);

grid(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'CameraUpVector',[0 0 1],'Color',[0 0 0],'DataAspectRatio',...
    [1 1 1],'Projection','perspective','XColor',[0.8 0.8 0.8],'YColor',...
    [0.8 0.8 0.8],'ZColor',[0.8 0.8 0.8]);
